const Resources = require( 'nodejs-core/resources' );

const CONSTANTS = {
	...Resources.CONSTANTS,
	API_CACHE_EXPIRE: 60, // 60 seconds
	ALLOW_FILE_SIZE: 20971520, // 20 mb
	UNIT: [
		'PACKAGE', 'PACKAGES',
		'POST', 'POSTS',
	],
	VAT: [ 0, 10 ],
	RATIO: [
		0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50,
		55, 60, 65, 70, 75, 80, 85, 90, 95, 100,
	],
	QUOTATION_STATUS: {
		PROCESSING		: 0,
		WAITING_APPROVAL: 1,
		APPROVED		: 2,
		CANCELLED		: 3,
		REJECTED		: 4,
	},
	PLAN_STATUS: {
		PROCESSING		: 0,
		WAITING_APPROVAL: 1,
		APPROVED		: 2,
		CANCELLED		: 3,
		REJECTED		: 4,
	},
	PROJECT_STATUS: {
		PITCHING		: 0,
		CONFIRMED		: 1,
		CONTRACTING		: 2,
		CONTRACTED		: 3,
		LIQUIDATION		: 4,
		PAYMENT_RECEIVED: 5,
		DELAYED			: 6,
		FAIL			: 7,
		DROPPED			: 8,
		DONE			: 9,
	},
	DISCOUNT_STATUS: {
		WAITING		: 0,
		CONFIRMED	: 1,
		REJECTED	: 2,
	},
	BILL_STATUS: {
		WAITING			: 0,
		PROCESSING		: 1,
		INVOICE_SENT	: 2,
		MONEY_COLLECTED	: 3,
	},
	PROCEDURE_STATUS: {
		WAITING		: 0,
		PROCESSING	: 1,
		CONFIRMED	: 2,
		DELAYED		: 3,
	},
	PAYMENT_STATUS: {
		WAITING		: 0,
		CONFIRMED	: 1,
		PAID		: 2,
	},
	PAYMENT_APPROVE_STATUS: {
		PROCESSING		: 0,
		WAITING_APPROVAL: 1,
		APPROVED		: 2,
		CANCELLED		: 3,
		REJECTED		: 4,
	},
	COST_MODIFICATION_STATUS: {
		WAITING	: 0,
		APPROVED: 1,
		VALID	: 2,
		REJECTED: 3,
	},
	PURCHASE_ORDER_STATUS: {
		PROCESSING		: 0,
		WAITING_APPROVAL: 1,
		APPROVED		: 2,
		CANCELLED		: 3,
		REJECTED		: 4,
		MODIFIED		: 5,
		FREEZED			: 6,
		DEFROST			: 7,
	},
	PROJECT_VO_STATUS: {
		PROCESSING		: 0,
		WAITING_APPROVAL: 1,
		APPROVED		: 2,
		CANCELLED		: 3,
		REJECTED		: 4,
	},
	PURCHASE_ORDER_APPROVE_STATUS: {
		WAITING_APPROVAL: 0,
		APPROVED		: 1,
		REJECTED		: 2,
	},
	VO_APPROVE_STATUS: {
		WAITING_APPROVAL: 0,
		APPROVED		: 1,
		REJECTED		: 2,
	},
	VO_ITEM_STATUS: {
		ADDED	: 0,
		REMOVED	: 1,
	},
	TRANSFER_TYPE: {
		CASH			: 0,
		BANKING_TRANSFER: 1,
		OTHER			: 2,
	},
	MODIFIED_STATUS: {
		ORIGIN	: 0,
		ADDED	: 1,
		REMOVED	: 2,
		EDITED	: 3,
	},
	DEFAULT_VAT						: 10,
	TOTAL_PROJECT_APPROVER			: 3,
	LEZO_RESIGNED_EMPLOYEE_STATUS	: 4,
};

module.exports = CONSTANTS;
